<?php

use Illuminate\Database\Seeder;

class NovelsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $novels = array(
            array('id' => '2','nome' => 'Sovereign of the Three Realms','chave' => 'SOTR'),
            array('id' => '3','nome' => 'The King’s Avatar','chave' => 'TKA'),
            array('id' => '5','nome' => 'Tales of Demons and Gods','chave' => 'TDG'),
            array('id' => '6','nome' => 'Martial God Asura','chave' => 'MGA'),
            array('id' => '11','nome' => 'Against the Gods','chave' => 'ATG'),
            array('id' => '12','nome' => 'World Defying Dan God','chave' => 'WDDG'),
            array('id' => '14','nome' => 'Heavenly Jewel Change','chave' => 'HJC'),
            array('id' => '15','nome' => 'Spirit Realm','chave' => 'SR'),
            array('id' => '16','nome' => 'The Legendary Moonlight Sculptor','chave' => 'LMS'),
            array('id' => '18','nome' => 'Seoul Station\'s Necromancer','chave' => 'SSN'),
            array('id' => '19','nome' => 'Martial God Space','chave' => 'MGS'),
            array('id' => '20','nome' => 'Renegade Immortal','chave' => 'RI'),
            array('id' => '22','nome' => 'Dungeon Defense','chave' => 'D.Defense'),
            array('id' => '23','nome' => 'I Was a Sword When I Reincarnated','chave' => 'IWSWIR'),
            array('id' => '25','nome' => 'Emperor’s Domination','chave' => 'ED'),
            array('id' => '27','nome' => 'Hail The King','chave' => 'HTK'),
            array('id' => '28','nome' => 'Swallowed Star','chave' => 'SS'),
            array('id' => '29','nome' => 'Warlock of the Magus World','chave' => 'WMW'),
            array('id' => '30','nome' => 'In Different World with Naruto System','chave' => 'IDWNS'),
            array('id' => '31','nome' => 'The Magus Era','chave' => 'TME'),
            array('id' => '35','nome' => 'Zero kara Hajimeru Mahou no Sho','chave' => 'ZeroKara'),
            array('id' => '36','nome' => 'The Last Nazi','chave' => 'TLN'),
            array('id' => '37','nome' => 'The Alchemist God','chave' => 'TAG'),
            array('id' => '38','nome' => 'Smartphone','chave' => 'Sto'),
            array('id' => '39','nome' => 'Hunter and Preys','chave' => 'HunPreys'),
            array('id' => '40','nome' => 'Apenas Uma Grandeza','chave' => 'AUG'),
            array('id' => '41','nome' => 'Entre as Estrelas','chave' => 'EaE'),
            array('id' => '42','nome' => 'Deus Demônio','chave' => 'DD'),
            array('id' => '43','nome' => 'Breakers','chave' => 'BKs'),
            array('id' => '44','nome' => 'Until Death','chave' => 'UD'),
            array('id' => '45','nome' => 'Kenja No Mago','chave' => 'KNM'),
            array('id' => '46','nome' => 'Bringing The Farm To Live In Another World','chave' => 'BFLAW'),
            array('id' => '47','nome' => 'My Wife Is A Beautiful CEO','chave' => 'CEO'),
            array('id' => '48','nome' => 'World Teacher','chave' => 'WT'),
            array('id' => '49','nome' => 'True Martial World','chave' => 'TMW'),
            array('id' => '51','nome' => 'Everyone Else is a Returnee','chave' => 'EER'),
            array('id' => '52','nome' => 'Princesa Consorte Chu [CHU WANG FEI]','chave' => 'CWF'),
            array('id' => '54','nome' => 'Konjiki no Word Master','chave' => 'KnW'),
            array('id' => '55','nome' => 'The Lazy King','chave' => 'TLK'),
            array('id' => '56','nome' => 'World Customize Creator','chave' => 'WCC'),
            array('id' => '57','nome' => 'Tate no Yuusha no Nariagari','chave' => 'TnY'),
            array('id' => '58','nome' => 'Sword of Emperor','chave' => 'SoE'),
            array('id' => '59','nome' => 'Elf Tensei Kara no Cheat Kenkoku-ki','chave' => 'Elf Tensei'),
            array('id' => '60','nome' => 'Tensei Shitara Slime Datta Ken','chave' => 'TSSDK'),
            array('id' => '61','nome' => 'Ore wa Ryouri to Kaji de Maou wo Honenuki ni Suru','chave' => 'DemonLord’s Pet'),
            array('id' => '62','nome' => 'Jikuu Mahou de Isekai to Chikyuu wo Ittarikitari','chave' => 'Jikuu Mahou'),
            array('id' => '63','nome' => 'Ubau Mono Ubawareru Mono','chave' => 'BOB'),
            array('id' => '64','nome' => 'Kamitachi ni Hirowareta Otoko','chave' => 'TMPG'),
            array('id' => '65','nome' => 'Gaikotsu Kishi-sama Tadaima Isekai e o Dekake-chuu','chave' => 'Skeleton Knight'),
            array('id' => '66','nome' => 'Manual da Chongfei','chave' => 'MCF'),
            array('id' => '73','nome' => 'The Legendary Thief','chave' => 'TLT'),
            array('id' => '74','nome' => 'Deus Marcial','chave' => 'DM'),
            array('id' => '76','nome' => 'Star Martial God Technique','chave' => 'SMGT'),
            array('id' => '78','nome' => 'Yuusha no Furi mo Raku Janai–Riyuu? Ore ga Kami dakara–','chave' => 'Yuusha Furi'),
            array('id' => '81','nome' => 'Era dos Adeptos','chave' => 'EdA'),
            array('id' => '82','nome' => 'The Lazy Swordmaster','chave' => 'TLS'),
            array('id' => '83','nome' => 'Deus Louco','chave' => 'DL'),
            array('id' => '86','nome' => 'The Log Experimental of the Crazy Lich','chave' => 'TLECL'),
            array('id' => '89','nome' => 'Blue Phoenix','chave' => 'BP'),
            array('id' => '90','nome' => 'Shura\'s Wrath','chave' => 'SW'),
            array('id' => '91','nome' => 'rebirth of  the thief who roamed the world','chave' => 'RT'),
            array('id' => '92','nome' => 'I’m Really a Superstar','chave' => 'IRAS'),
            array('id' => '93','nome' => 'The Great Ruler','chave' => 'TGR'),
            array('id' => '94','nome' => 'Stellar Transformation','chave' => 'ST'),
            array('id' => '95','nome' => 'Mundo Marcial','chave' => 'MM'),
            array('id' => '96','nome' => 'Verdadeiro Mundo Marcial','chave' => 'VMM'),
            array('id' => '97','nome' => 'Grande Rei Demônio','chave' => 'GRD'),
            array('id' => '98','nome' => 'Os Nove Caldeirões','chave' => 'ONC'),
            array('id' => '99','nome' => 'O Grande Ladrão','chave' => 'OGL'),
            array('id' => '101','nome' => 'Lorde Xue Ying','chave' => 'LXY'),
            array('id' => '102','nome' => 'O Grande Governante','chave' => 'OGG'),
            array('id' => '103','nome' => 'O Rei do Campo de Batalha','chave' => 'ORCB'),
            array('id' => '104','nome' => 'Trono Divino','chave' => 'TD'),
            array('id' => '105','nome' => 'Trono do Arcanista','chave' => 'TA'),
            array('id' => '106','nome' => 'Liberte Aquela Bruxa','chave' => 'LAB'),
            array('id' => '107','nome' => 'Re:Monster','chave' => 'RM'),
            array('id' => '112','nome' => 'Deuses Caídos da Criação','chave' => 'DCC'),
            array('id' => '115','nome' => 'a  step into pass','chave' => 'asip'),
            array('id' => '116','nome' => 'God of Crime','chave' => 'GOC'),
            array('id' => '117','nome' => 'Lang feng and his perv adventures!','chave' => 'LFHPA'),
            array('id' => '119','nome' => 'The Amber Sword','chave' => 'TAS'),
            array('id' => '127','nome' => 'Evolução Global','chave' => 'EG'),
            array('id' => '128','nome' => 'Soberano do Julgamento','chave' => 'SJ'),
            array('id' => '129','nome' => 'Rei Macaco Imortal','chave' => 'RMI'),
            array('id' => '130','nome' => 'Renascimento do Demônio Celestial','chave' => 'RDC'),
            array('id' => '131','nome' => 'Wu Dong Qian Kun','chave' => 'WDQK'),
            array('id' => '134','nome' => 'Crônicas das Guerras Primordiais','chave' => 'CGP'),
            array('id' => '135','nome' => 'Infinity Armament','chave' => 'IA'),
            array('id' => '140','nome' => 'Dark Net Galática','chave' => 'DNG'),
            array('id' => '141','nome' => 'Escolha Absoluta!','chave' => 'EA!'),
            array('id' => '142','nome' => 'Louvem o Orc (Praise the Orc)','chave' => 'PTO'),
            array('id' => '146','nome' => 'Morte Instantânea (??)','chave' => 'MI'),
            array('id' => '151','nome' => 'Seirei Tsukai no Blade Dance','chave' => 'STBD'),
            array('id' => '152','nome' => 'o Ultimo Herdeiro da Luz','chave' => 'UHL'),
            array('id' => '153','nome' => 'Library of Heaven\'s Path','chave' => 'LHP'),
            array('id' => '154','nome' => 'Aguerradosducados','chave' => 'AGD'),
            array('id' => '155','nome' => 'Chronicles of Primordial Wars','chave' => 'CPW'),
            array('id' => '156','nome' => 'I Have a Mansion in the Post-Apocalyptic World','chave' => 'IHMPAW'),
            array('id' => '157','nome' => 'The Book Eating Magician','chave' => 'TBEM'),
            array('id' => '158','nome' => 'Evil-Like Duke Household','chave' => 'ELDH'),
            array('id' => '161','nome' => 'The Legendary Master\'s Wife','chave' => 'TLMW'),
            array('id' => '165','nome' => 'God and Devil World','chave' => 'GDW'),
            array('id' => '166','nome' => 'Todori wa seitokai ','chave' => 'TWS'),
            array('id' => '168','nome' => 'Lenda do Rei Dragão','chave' => 'LRD'),
            array('id' => '169','nome' => 'Matador de Goblins','chave' => 'MdG'),
            array('id' => '170','nome' => 'Mundo Perfeito','chave' => 'MP'),
            array('id' => '171','nome' => 'Portão da Revelação','chave' => 'PdR'),
            array('id' => '172','nome' => 'HORIGIC NO MAGIC','chave' => 'HxM'),
            array('id' => '179','nome' => 'God Of Soul System','chave' => 'GOSS'),
            array('id' => '180','nome' => 'ancient godly monarc','chave' => 'agm'),
            array('id' => '184','nome' => 'The Avalon of Five Elements','chave' => 'AFE'),
            array('id' => '185','nome' => 'Age of Adepts','chave' => 'AoA'),
            array('id' => '186','nome' => 'Doomed to be Cannon Fodder','chave' => 'DCF'),
            array('id' => '187','nome' => 'Knights and Kings','chave' => 'K&K'),
            array('id' => '189','nome' => 'Invincible','chave' => 'IVE'),
            array('id' => '191','nome' => 'The Great Thief','chave' => 'TGT'),
            array('id' => '192','nome' => 'MMORPG: Rebirth of The Legendary Guardian','chave' => 'RLG'),
            array('id' => '196','nome' => 'Patrulheiro Noturno','chave' => 'PN'),
            array('id' => '197','nome' => 'Overgeared','chave' => 'OG'),
            array('id' => '200','nome' => 'Evil Dragon Reincarnation ( Jaryuu Tensei )','chave' => 'EDR'),
            array('id' => '201','nome' => 'Shikkaku Mon No Saikyou Kenja','chave' => 'SMNSK'),
            array('id' => '202','nome' => 'Arifureta: Do Comum ao Mais Forte do Mundo','chave' => 'Arifureta'),
            array('id' => '203','nome' => 'Ultimate Scheming System','chave' => 'USS'),
            array('id' => '204','nome' => 'Divine Throne of Primordial Blood','chave' => 'DTPB'),
            array('id' => '205','nome' => 'The Strongest Legend of Dragon Ball','chave' => 'TSLDB'),
            array('id' => '206','nome' => 'Super Gene','chave' => 'SG'),
            array('id' => '207','nome' => 'Battleship AI','chave' => 'BSAI'),
            array('id' => '208','nome' => 'Dawn Traveler','chave' => 'DT'),
            array('id' => '209','nome' => 'Beyond?','chave' => 'BYD'),
            array('id' => '211','nome' => 'Child of Light','chave' => 'COL'),
            array('id' => '212','nome' => 'Chaotic Lightning Cultivation','chave' => 'CLC'),
            array('id' => '213','nome' => 'History\'s Strongest Senior Brother','chave' => 'HSSB'),
            array('id' => '214','nome' => 'Revolution of the 8th Class Mage','chave' => 'R8CM'),
            array('id' => '215','nome' => 'Star Rank Hunter','chave' => 'SRH'),
            array('id' => '216','nome' => 'Stranger’s Handbook','chave' => 'SH'),
            array('id' => '217','nome' => 'The Strongest Gene','chave' => 'TSG'),
            array('id' => '218','nome' => 'Zhan Long','chave' => 'ZL'),
            array('id' => '219','nome' => 'Deuses Imortais','chave' => 'DI'),
            array('id' => '221','nome' => 'Setes','chave' => '7th'),
            array('id' => '223','nome' => 'Long Live Summons','chave' => 'LLS'),
            array('id' => '227','nome' => 'Red Envelope Group of the Three Realms','chave' => 'REGR'),
            array('id' => '228','nome' => 'Douluo Dalu 2 – Jueshi Tangmen','chave' => 'DDU2'),
            array('id' => '229','nome' => 'Dreadful Radio Game','chave' => 'DRG'),
            array('id' => '230','nome' => 'My MCV and Doomsday','chave' => 'MMD'),
            array('id' => '231','nome' => 'NEET Receives a Dating Sim Game Leveling System','chave' => 'NRDSS'),
            array('id' => '233','nome' => 'Nine Heavenly Star Art','chave' => 'NHSA'),
            array('id' => '234','nome' => 'Peerless Battle Spirit','chave' => 'PBS'),
            array('id' => '235','nome' => 'Glutton Berserker','chave' => 'GB'),
            array('id' => '236','nome' => 'Hai to Gensou no Grimgar','chave' => 'HGG'),
            array('id' => '237','nome' => 'Monster Paradise','chave' => 'MTP'),
            array('id' => '238','nome' => 'A Record of a Mortal’s Journey to Immortality ','chave' => 'ARMJI'),
            array('id' => '239','nome' => 'Ancient Strengthening Technique ','chave' => 'AST'),
            array('id' => '240','nome' => 'Lord of All Realms','chave' => 'LOAR'),
            array('id' => '241','nome' => 'Quickly Wear the Face of the Devil ','chave' => 'FOD'),
            array('id' => '242','nome' => 'Evil Emperor’s Wild Consort','chave' => 'EEWC'),
            array('id' => '243','nome' => 'A Will Eternal','chave' => 'AWE'),
            array('id' => '244','nome' => 'Pursuit of the Truth','chave' => 'POTT'),
            array('id' => '245','nome' => 'Tales of the Reincarnated Lord','chave' => 'TOTRL'),
            array('id' => '247','nome' => 'King of Gods','chave' => 'KOG'),
            array('id' => '248','nome' => 'The Beginning After The End','chave' => 'TBATE'),
            array('id' => '249','nome' => 'Battle Through the Heavens','chave' => 'BTTH'),
            array('id' => '250','nome' => 'Red Storm','chave' => 'RS'),
            array('id' => '251','nome' => 'World of Immortals','chave' => 'WOI'),
            array('id' => '252','nome' => 'Charm of Soul Pets','chave' => 'COSP'),
            array('id' => '253','nome' => 'Limitless Sword God','chave' => 'LSG'),
            array('id' => '254','nome' => 'Shen Yin Wang Zuo','chave' => 'SYWZ'),
            array('id' => '255','nome' => 'Cult of the Sacred Runes','chave' => 'COTSR'),
            array('id' => '256','nome' => 'Martial World','chave' => 'MW'),
            array('id' => '257','nome' => 'Panlong','chave' => 'PLG'),
            array('id' => '258','nome' => 'A Crônica de Eastar','chave' => 'ACDE'),
            array('id' => '259','nome' => 'A Guerra dos Nove Mundos','chave' => 'AGDNM'),
            array('id' => '260','nome' => 'O Setimo Zorgnatron','chave' => 'OSZ'),
            array('id' => '261','nome' => 'Ascensão de um Deus','chave' => 'ADUD'),
            array('id' => '262','nome' => 'Pacto de Sangue','chave' => 'PDS'),
            array('id' => '263','nome' => 'Deus Imperador dos Taos','chave' => 'DIDT'),
            array('id' => '264','nome' => 'O Herdeiro do Mundo','chave' => 'OHDM'),
            array('id' => '265','nome' => 'Mundo dos Titãs','chave' => 'MDT'),
            array('id' => '266','nome' => 'The King of the Battlefield','chave' => 'KOTB'),
            array('id' => '267','nome' => 'Ze Tian Ji','chave' => 'ZTJ'),
            array('id' => '268','nome' => 'Arifureta Shokugyou de Sekai Saikyou','chave' => 'ASSS'),
            array('id' => '269','nome' => 'Dragoon: Ryuu Kishi e No Michi','chave' => 'DRKBN'),
            array('id' => '270','nome' => 'Gomen ne, Onii-sama!','chave' => 'GNO'),
            array('id' => '271','nome' => 'Growth Cheat','chave' => 'GC'),
            array('id' => '272','nome' => 'Murabito Desu Ga Nani Ka?','chave' => 'MDGNK'),
            array('id' => '273','nome' => 'Sono mono. Nochi ni…','chave' => 'SMNN'),
            array('id' => '274','nome' => 'Tensei Shitara Ken Deshita','chave' => 'TSKD'),
            array('id' => '275','nome' => 'Bu ni Mi wo Sasagete Hyaku to Yonen. Elf de Yarinaosu Musha Shugyou','chave' => 'BMSHYEYMS'),
            array('id' => '276','nome' => 'Kamigoroshi no Eiyuu to Nanatsu no Seiyaku','chave' => 'KENS'),
            array('id' => '277','nome' => 'Awakening','chave' => 'AWK'),
            array('id' => '278','nome' => 'Main Character Hides His Strength','chave' => 'MCHHS'),
            array('id' => '279','nome' => 'Maou No Hajimekata','chave' => 'MNH'),
            array('id' => '280','nome' => 'Kara no Kyoukai','chave' => 'kk'),
            array('id' => '281','nome' => 'Mahouka Koukou no Rettousei','chave' => 'MKR'),
            array('id' => '282','nome' => 'Toaru Majutsu no Index','chave' => 'TMI'),
            array('id' => '283','nome' => 'This World with Cut & Paste','chave' => 'TWWCP'),
            array('id' => '286','nome' => 'Paraíso Apocalíptico ','chave' => 'PA'),
            array('id' => '287','nome' => 'Ranger Noturno','chave' => 'RN'),
            array('id' => '288','nome' => 'Rivais do Infinito','chave' => 'RDI'),
            array('id' => '289','nome' => 'Soberania ','chave' => 'SB'),
            array('id' => '290','nome' => 'Pele Verde','chave' => 'PV'),
            array('id' => '291','nome' => 'Ziqin','chave' => 'Ziqin'),
            array('id' => '292','nome' => 'Aelis','chave' => 'Aelis'),
            array('id' => '293','nome' => 'Perfect World','chave' => 'PW'),
            array('id' => '294','nome' => 'Gamers!','chave' => 'GMs!'),
            array('id' => '295','nome' => 'Kimi no Suizou wo Tabetai','chave' => 'Pâncreas'),
            array('id' => '296','nome' => 'Magi Craft Meister','chave' => 'MCM'),
            array('id' => '297','nome' => 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e','chave' => 'YouJitsu'),
            array('id' => '298','nome' => 'Jaku-chara Tomozaki-kun','chave' => 'Jaku-chara'),
            array('id' => '299','nome' => 'He’s the Legendary Guard, Isn’t He?','chave' => 'HLG'),
            array('id' => '302','nome' => 'Doom Lord','chave' => 'Doom Lord'),
            array('id' => '303','nome' => 'Great Demon King','chave' => 'GDK'),
            array('id' => '305','nome' => 'Global Evolution','chave' => 'GE'),
            array('id' => '306','nome' => 'Gate of Apocalypse','chave' => 'GOA'),
            array('id' => '307','nome' => 'God Of Thunder','chave' => 'GOT'),
            array('id' => '308','nome' => 'Horizon, Bright Moon, Sabre','chave' => 'HBMS'),
            array('id' => '309','nome' => 'Heroes Shed No Tears','chave' => 'HSNT'),
            array('id' => '311','nome' => 'Killing Grounds of Gods and Devils','chave' => 'KGGD'),
            array('id' => '313','nome' => 'So What If It’s an RPG World?','chave' => 'RPG'),
            array('id' => '315','nome' => 'Sheng Wang','chave' => 'Sheng Wang'),
            array('id' => '316','nome' => 'Super Soldier King','chave' => 'SSK'),
            array('id' => '318','nome' => 'The Dark King','chave' => 'TDK'),
            array('id' => '319','nome' => 'My Beautiful Teacher','chave' => 'Teacher'),
            array('id' => '321','nome' => 'The Trembling World','chave' => 'TTW'),
            array('id' => '322','nome' => 'The Ultimate Evolution','chave' => 'TUE'),
            array('id' => '323','nome' => 'Virtual World: Unparalleled under the Sky','chave' => 'VW'),
            array('id' => '348','nome' => 'Acquiring Talent in a Dungeon','chave' => 'ATD'),
            array('id' => '349','nome' => 'Big Life','chave' => 'Big Life'),
            array('id' => '351','nome' => 'Demon King &amp; Hero','chave' => 'DK &amp; H'),
            array('id' => '352','nome' => 'Dimensional Sovereign','chave' => 'DS'),
            array('id' => '353','nome' => 'Emperor of Solo Play','chave' => 'ESP'),
            array('id' => '354','nome' => 'Evolution Theory of the Hunter','chave' => 'ETH'),
            array('id' => '355','nome' => 'The First Hunter','chave' => 'First Hunter'),
            array('id' => '356','nome' => 'God’s Song','chave' => 'God’s Song'),
            array('id' => '357','nome' => 'Haroon','chave' => 'Haroon'),
            array('id' => '359','nome' => 'Hunter of the Ruined World','chave' => 'HTRW'),
            array('id' => '360','nome' => 'I Am the Monarch','chave' => 'IAM'),
            array('id' => '361','nome' => 'Infinite Competitive Dungeon Society','chave' => 'ICDS'),
            array('id' => '362','nome' => 'I’m Sorry For Being Born In This World!','chave' => 'ISBBTW'),
            array('id' => '364','nome' => 'Life Howling','chave' => 'Life Howling'),
            array('id' => '365','nome' => 'Lv1 Skeleton','chave' => 'Lv1 Skeleton'),
            array('id' => '367','nome' => 'Master Hunter K','chave' => 'MHK'),
            array('id' => '368','nome' => 'Max Level Newbie','chave' => 'MLN'),
            array('id' => '369','nome' => 'A Monster Who Levels Up','chave' => 'MWLU'),
            array('id' => '373','nome' => 'Reader','chave' => 'Reader'),
            array('id' => '374','nome' => 'Reincarnator','chave' => 'Reincarnator'),
            array('id' => '375','nome' => 'Sovereign of Judgement','chave' => 'SOJ'),
            array('id' => '376','nome' => 'Taming Master','chave' => 'Tama'),
            array('id' => '377','nome' => 'The Hero','chave' => 'The Hero'),
            array('id' => '379','nome' => 'The Tutorial Is Too Hard','chave' => 'Tutorial'),
            array('id' => '380','nome' => 'When God Made Me','chave' => 'WGMM'),
            array('id' => '382','nome' => 'Blade Online','chave' => 'Blade Online'),
            array('id' => '384','nome' => 'Boku wa Isekai de Fuyo Mahou to Shoukan Mahou wo Tenbin ni Kakeru','chave' => 'Boku Wa Isekai'),
            array('id' => '385','nome' => 'The Dungeon Seeker','chave' => 'Dungeon Seeker'),
            array('id' => '386','nome' => 'Goblin Kingdom','chave' => 'GK'),
            array('id' => '387','nome' => 'Hokuou Kizoku to Moukinzuma no Yukiguni Karigurashi','chave' => 'Hokuou Kizoku'),
            array('id' => '388','nome' => 'Because Janitor-san Is Not a Hero','chave' => 'JNH'),
            array('id' => '389','nome' => 'Kumo Desu ga, Nani ka?','chave' => 'KDGNK'),
            array('id' => '390','nome' => 'Katte Kita Motoyuusha','chave' => 'KKM'),
            array('id' => '391','nome' => 'Lazy Dungeon Master','chave' => 'Lazy Dungeon Master'),
            array('id' => '392','nome' => 'Legend','chave' => 'LEGEND'),
            array('id' => '393','nome' => 'I Who Is a Loner, Using Cheats Adapts to the Dungeon','chave' => 'Loner Dungeon'),
            array('id' => '394','nome' => 'Master Of Monster','chave' => 'Master of Monster'),
            array('id' => '395','nome' => 'Maken no Daydreamer','chave' => 'MND'),
            array('id' => '397','nome' => 'NEET dakedo Hello Work ni Ittara Isekai ni Tsuretekareta','chave' => 'NEET'),
            array('id' => '398','nome' => 'No Fatigue &#8211; 24 Jikan Tatakaeru Otoko no Tenseitan','chave' => 'No Fatigue'),
            array('id' => '399','nome' => 'Riot Grasper ~Stealing Skills in the Otherworld~','chave' => 'Riot Grasper'),
            array('id' => '400','nome' => 'Seirei Gensouki ~Konna Sekai de Deaeta Kimi ni~','chave' => 'Seirei Gensouki'),
            array('id' => '401','nome' => 'Sendai Yuusha Wa Inkyou Shitai','chave' => 'Sendai Yuusha'),
            array('id' => '402','nome' => 'Shikkaku Mon no Saikyou Kenja~ Sekai Saikyou no Kenja ga Sarani Tsuyoku Naru Tameni Tenseishimashita~','chave' => 'Shikkaku Mon'),
            array('id' => '403','nome' => 'In a Different World with a Smartphone','chave' => 'Smartphone'),
            array('id' => '404','nome' => 'Shinka No Mi','chave' => 'SNM'),
            array('id' => '405','nome' => 'Seijo no Kaifuku Mahou ga Dou Mitemo Ore no Rekkaban na Ken ni Tsuite','chave' => 'SRM'),
            array('id' => '406','nome' => 'Skill Taker’s World Domination ~ Building a Slave Harem from Scratch','chave' => 'STWD'),
            array('id' => '407','nome' => 'That Person. Later on…','chave' => 'That Person'),
            array('id' => '409','nome' => 'Toaru Ossan no VRMMO Katsudouki','chave' => 'Toaru Ossan'),
            array('id' => '410','nome' => '(Um, Sorry) I’ve Been Reincarnated!','chave' => 'Um Sorry'),
            array('id' => '411','nome' => 'World Teacher – Other World Style Education &amp; Agent','chave' => 'World Teacher'),
            array('id' => '412','nome' => 'Yomigaeri no Maou','chave' => 'YNM'),
            array('id' => '413','nome' => 'kujonin','chave' => 'exterminator'),
            array('id' => '414','nome' => 'Re:Zero kara Hajimeru Isekai Seikatsu Ex','chave' => 'RZEX')
        );

        foreach($novels as $novel){
            $novel = App\Novel::Create([
                'titulo' => $novel['nome'],
                'sigla' => $novel['chave'],
                'sinopse' => '',
                'linguagem_id' => '1',
                'tipo_id' => '1',
                'url' => str_slug($novel['nome'])
            ]);
        }
    }
}
