language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: PnjVVpPdfbv6VdyV91/mcjklUO+lkbXr+dCalUUjZsDEujVMu/xWBlKakRgr7OdbXrx/ply+5nFhjHgNTK7G7nmX5JGmpdLpgVcSTE3VRgIKyg4GdLNsV5INJAUI2+lYdEfUkgR1U1ZttWENqxTgLwT8X1phg6gYN9iAl/AnJflTxsXVxQjnSC1/cmdPgIvX+fbReLkiJyT7afcHD75F2uLQ1IA0OF9mHSGKqwlVSNyWJEQJcG4eLUyPOYWIGPQZezk5w/aw5j9UFWqyIjueuVQDWEnog8hv0lpRTzhVnFlcLCneQr2sbBwYnaKxG44gKxj9/jOsrxl9l+9MqjxxsWcjWGqwIODK8S7/vMcp0cuTnM2IKaD6CPHUIHRUt0cuToT2jN1yBeXQwq8zuvs2rCrZvmumkE39ohLTll72ZslhbJX+zDlJhSTiml91s6S+YH08qlrlLNtoMBpxkqfRXxGUQrvrHbxuHj0x9m8lkcxu1utsW3gSSR+/Pvy+HLW+KVHoYQNpuot19p6HFp7n/s66Avvign9suMCHFUmH0/WZHj/5pCtxyAR4+t7DYRimUP7VyXYfUqKokyeoO+hOOpF/CbtzHLcTsjhu8Rd06CJctH7bk8il06ejSziJdJsUd8t8g2z6SSbrjPr7PPx7MqfqRjqYdGn4ZWKn9X5sAEo=
  app: centralnovel
