language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: Mxy3M+87fUuynoX84rFgIS7EWM11zTPpEzYb0Axh0w0aBHaaOEev9aK41dyriFc8tcHFy7i9PC48bG/mMmkxsCXtvg4PznXQhA3DuCjD247uJ6xNveqapSV7magPTKDaS1qBDWjSxg+r3UFHP2aPjfhWSnrE1O3Pc70/Q2v97jnEYOnE4fkIfxpSdXJlPHvujI0JyyTr3RHLgk/5ZAMrsDFNlrOplNnSRMS0Up9u2rlshJpaj+k+xv0mzcPmoS0ifvChkIqQCctRktFXd/H49vPezmWoE7ZNFkBlAfbV5PCRNgyH2545Ml5IB/oHCqyu191xbOK1SO12m+LY635bMLO4MolizUUqWYTTJFaIHHZd9OoXRqwvA/fCDa8PbsgV4tmhgfIQV6pRJlgU4lyjKHrN+lSfrbA3ZVmoDwfYKEI9I4vZ4E0nZkT9fK6xJVXFZL+tpECHKo9FTP9CwgRPJEIvswWo+E4+6oI9zWiHR3J4q/1sLtHRptCKAuyKlNOuocz03tdbmNUhsEugIyREv7ZFrgU3GHC6foIgiXL+29JPr6Hdd9t1KL2OUlOkqid/wydJEMakbemM5jGywi14OVYrHk3UGy1D0G5ddszcs2FgQ/ShXH2LIU3PnNGBgk41cn+g28dN+2bvkxw75N06jUmoh4hj+Kx8eYkfLlmiCok=
  app: centralnovel
  on:
    repo: luizotavior/centralnovel
