language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: dtYtLks/mRrmYwmSl3E2BhAc1iRdgvf/OXgs7tNQqA+Bb4GASITkYzN/6Puau5wghnMf8kQXJob+bhZiincuvPYu4YZqufpR6exL3mqCgoVc9PTVrB7Ts74g05ZawYdpXZbpaJYqniwxNe28nMiKCqwxu1q9IrJiHZOHTtxwkxsQVLXJDJ4xiHnG5oKzOhdugEIaY/kP+QiFW6Q1t7SQIckPsbrDv7qb92WFLWMuMaPP+BkmJjZTv+Y3RbcPBL6gHiprUnHX6Pn3DNujbsoPg4JOmjaAvasGKJaeSB0SLSKWucAN1bxHR2mCiVyMNDd/AvYkt3At/86+uujCsqwHVXdIV/xxvDKgWSeWKDRV1szj7Byc3TDu3LGGUeFMFaInjp5Xc7jEjc/Q4T7z4OS/7Mg2qsuWOZI7OWlGXA1KgNUcfey0j7VNR3qK0dcCd4uZWxPuk27FeTD4cgYfwATUgnh8eku4luUG6s+kMyDh0JdZ6kY/IOOze44aTyJq48B19QoGWVAAhrlwu0mmnWaHG50Zm55mevnHkAw60/ooN2nAxBT9pAeLuMJLzB9OvN4c5YDT0a6zg62WAeT3Lqwa7ZDhk1O4LxNYnJZWRnCeJlrNZcA+JB71Drf6h0AnZuLly+ysr80h/+jCtW11oGhzR+7vkZgvml58GsvWbCK05yQ=
  app: centralnovel
