language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run generate
deploy:
  provider: heroku
  api_key:
    secure: s5Qax3vWDpzUSBBrSVM0SCeFGl+wy+rWy8Qxlt0WL/yfVfllWTPR9h5eZJ1Kl59wEws1u7/plMsPOu1/BQHfpedekH6/AgtGGKLP8SQ3Rju90RFvhBGiRj74l7J77UzHHvtp2Yu1+Qj01gHai8LaYjLqd4RZIhqkMA7O2Ml2eWL7b0bcXU9Y0aE1hdZm9P5WAmQ9LX3a46gWUOHe2W+r3wKcWMMSV/xi/tOyPzrHn20Vh3IaUVL6LLkOS9irKL1FuAzVvgIPldvSjG0N3Qfq3qk3PEDh/4QstxHpA/Ka1KwO+ZMDgLQb8guv5CLDAD35dLWEW4W12AHDG4ngWjSwem1jRx8VBGpqV2oSjZiV9mnY4MBXYtlFDxSBzfmN0wnVhkajPmcn+eYhQmVAsZxXrQko9IChSzYsuxqJkWpuBswEM4Na+IGRAP7SQKhlOC9W/r7vpEQJO+Pdg6hK7ojqKyz6SOsx1fCBualSxapIfagXBh30s89f+rttTOBkXIiSx9Et71RTBkq7WxQCXSYlBS6ANmbYvtth8M+EHEKBshk6fgXGz85ZbPd+rqFM797uf3uCqlV+ec9urCGsmFbnESQUYYyjKYQwZDPUSHeAusvBeVnimTieFAdgcaASih6XannljLfIauV3FscvHtTAgA7TJg7uEs+D/LvAdUGs93E=
  app: centralnovel
