language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: GvrWEv5QuV8TiBrzwEVZoE7EBCwZ6KKrWWlgBThTSdeiNoJdXSR/4pV7xIQ6hUG1RE1kEo5SUvM6eb84XsMINYTc03NB3poL0MxTv/ti+PO7HQXKSq/p8BbT+0RSCTDlsjbqNK+VKCzaV3VTCCPCaSTjDIyp8vDl/NqQDTwW7O/l4KA7A5DNrArmOXelDGXfk0rDqATvKBoP17+34cbfBQuKHPZyxZZ35OIwhBDwnt2IgPzkTIwa10XRH7vgYJaD+srK6C6XMxa/fF0vj3mKWLiOqeKZ4+QxeArUtWbmO6XN3hHYCdI3Pcb+txuwSEk0Df8Hv5CK2yIZmSz7ONrC7K5xFZ6kR2dFjYzNDEsCbJpZVCd3P+nmDQN9pxSYA+yNdCKTEdypBrYOTMnyp9MZFaXhxqdOhZWMJb7c8Kmcw0KSPgsnd1a1l8G5f+ReLKSTl6B8VNJsiyXZqXqQR9evnTns3xZBCYaDcZ7LW+zJnimxt66ZOzEsnwTAtFxSpBqDI332HUIjeBmGJM0k8wS4M1EebXW+sEL1KNpcjEeco7Sk1t4WjRJTWujcNYWiqo55L8DK3+yqEbLMxvM4l5bZK/avMyUwqhqvvbdjiJYiLuj3ODJrsDriBKUJstuvbxbf8NAZ6U9MooSkyU5qwKBDvO7wH7YbEXcTl8ILSe/npes=
  app: centralnovel
