language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: pdeH7yexaDPA4hzwFB12YI4jz988uwToGmmrJC8Q9/Fiype3g0NtclBbYA5nduOH4y2V6SRf2zVV507Tk7Bycc5wKlSdkvpMC/81Nxr1tPkX4TlVAQfp/WvHtgc77TD/OXdzWJ2Nx+8qcrhxbDUPGx/xOmLayXju1zrCRyOMjeLf7+mBvn71w6Hk5QE8mboqrSB/+RhDra23eUp9BGu28GX5yW8Xj89yno1D4PA/nHaeAxqtN1CMF+0VuM0LXlm4A7lPHlfbsUO6ESp6T7bOx7kJ2UhVXaYOawnPFdGG7kQ6NHodUikDN/2Sj5SuRi6LbVXDIhgD/EeXR6fUp8QVLNiA5sWEiAIOUFjK33KGtyIf8pKPJ+PeroEenut3bqLa8qZLQ08VMFPJQd+EP2s1okoEmdwSZRxAaJhDcARIRgP76U6ofcxFKTNAuZ/ST4IiCeyRbvBg7lUqFxggsaynbdhdLfwHHy/8V9ibKPMZOyeGdum61Cl3fqJf/qUof0JBLwLHmMKj6roQS6ODYHEU3EethNtUoOHWJEX4bnNQRAQn3l5Cqnzw5eBltyMv73DULpDk3xhi6qQmGMCuspc5nmtL/bGNKLh66LkF19Q65geiZXVoNnkkamCMRIfTBV59NnxPuesWMRPUB9cXZcjo0+HY8tZDow6Ik1vlAU2lPDo=
  app: centralnovel
