language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm run generate
deploy:
  provider: heroku
  api_key:
    secure: mFH536ivuoN4hITrPZ6V/JsQDXqv+g3f6TorFuJQu6mOiDGwEnIgNtkD+6Jc77ufIufhCjDhO0cV3BpbX3CJJmwGRoJSiyZmSjnQvwUT+fkhKhk7S98liW6f/ovQiSrA/5xyETraFn/m5uFZGaxT6Bx7/+JBhzLVIH09herw4R1yFZyl6zUOPf13AFZmBtFCfKT/gpHMM67UQB3LnIYyomAdbGgtOGgnYxvTKTIJpJargPQ+o2kzUUwfYtEdaKv4MCgIxAQ3Gc8SvhEIBXRxSrRD/6I+x6LpDuEyFlBNiV4RSTdP31AC0W9cV4GmysdVVnuIbG8E/XSzDT6faKVxQK8TBeUDlKgDvB1l1Op5PprwPnleepzvd+k205UU9UetKfcrORZAm0aBvsqWtqFtqoYmzvPOKiE69iAmheOWnC4xQwqY0W3u9BFDzrysEpLFO6YBVmVkoAyfLTpK9Q2RdiLAwXn1TZohOo17XcMKWU7+tjlTJaLLDIuyHj90IYLZIvg0qZ9f+uibNTVjfDfu+I76yreTG1fssDWcSLVaiwv/GN/3tQa5Qn0s8FarS2WtCRdAvrDXGXbOR5bU5T9dm/IylsAmldDMh4NXLyOE2/dbg1xp7nThyDD/2rImMLRhHbzItK2lO1GESDFMqo0PovfXDMml7lp6HsCA1Pzc4MU=
  app: centralnovel
