<template>
  <main>
    <no-ssr>
      <agile
        :autoplay="false"
        :autoplaySpeed="6000"
        :arrows="false"
        :dots="false"
        :infinite="true"
      >
        <div class="slide">
          <img
            src="images/slides/slide_00.png"
            alt=""
          >
        </div>
      </agile>
    </no-ssr>
  </main>
</template>
